name: Docker

env:
  OP_VERSION: "11"
  DOCKER_ORG: "dabbleofdevops"
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:

  publish-dev:
    # restrict this job to base repo for now
    runs-on: ubuntu-latest
    env:
      INPUT_BUILDOPTIONS: --pull
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set Job Environment Variables
        run: |
          CALVER="$( date -u '+%Y.%m.%d' )"
          SHA7="${GITHUB_SHA::7}"
          DOCKER_TAG="op-v${OP_VER}-dodo-${SHA7}"
          IMAGE_SPEC="${DOCKER_ORG}/openproject-community:${DOCKER_TAG}"
          echo "CALVER=${CALVER}" >> $GITHUB_ENV
          echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV
          echo "IMAGE_SPEC=${IMAGE_SPEC}" >> $GITHUB_ENV
      - name: Prepare docker files
        run: |
          cp ./docker/prod/Dockerfile ./Dockerfile
      - name: Build & Push
        id: build_and_push
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: openproject/community
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_semver: true
      - name: Test
        run: |
          docker run --name openproject -d -p 8080:80 -e SUPERVISORD_LOG_LEVEL=debug -e SECRET_KEY_BASE=secret ${{ steps.build_and_push.outputs.digest }}
          sleep 30
          docker logs openproject --tail 100
          wget -O- --retry-on-http-error=503,502 --retry-connrefused http://localhost:8080/api/v3
